repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    -   id: bandit
        args: ["-ll", "-ii"]  # Only medium/high severity and confidence

-   repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
    -   id: pip-audit
        args: ["--desc", "on"]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
